### PR TITLE
TypedArray::create API accept length or slice

### PR DESCRIPTION
**Pull request by simon-whitehead**
Issue: https://github.com/servo/rust-mozjs/issues/336

Changes `TypedArray::create` signature to accept a new `CreateWith` argument in place of the `length` and `data` arguments.

Includes similar tests to what was already there using the new enum.

Some notes:

* My first Servo PR. Yay!
* Rustfmt seems to have made some changes. Not sure if thats a problem. The license `/* */` block comments are now `//` single line comments. And some other multi-line code has been changed to single line code. If this is an issue let me know and I'll disable rustfmt and revert those changes back.
* I didn't bump the crate version. I am not sure about the process around that and looking at other PRs I've noticed none of those bumped the version number either.
* I don't yet understand how this applies to Servo. From what I can see everything uses the macro and not `TypedArray::create` directly. I may have missed something though.

Feedback welcome.

@jdm - tagging you since you opened the issue (I hope thats okay?)

---
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-mozjs/337)

### CODE REVIEW

**Comment by simon-whitehead** [comment]
Also one other potential noteworthy change.

The original tests allowed different `length` and `data` length inputs. For example, `create` with a length of 10 but a slice with length 5 would result in a 0 padded slice with a length of 10.

The issue itself seems to suggest this shouldn't be possible and so after the change was made, this situation wasn't possible and I have updated the existing tests to reflect that.

**Comment by jdm** [comment]
There are uses of ArrayBuffer::create and Uint8ClampedArray::Create and in Servo right now, and https://github.com/servo/servo/pull/15427 adds more typed array creation.

**Comment by jdm** [comment]
This looks great! Thank you for working on this!
@bors-servo: r+

**Comment by simon-whitehead** [comment]
No problem! Thanks for merging so quickly! :smiley:

(Ps: this was such a painless process. I will look out for more issues I can help with :+1:)

**Pull request merged**
