### PR TITLE
Error reporting strings are Latin1, not UTF-8.

### PR DESCRIPTION
**Pull request by eefriedman**
Because the best way to convert from a 16-bit encoding to an 8-bit
encoding is obviously truncation.

[Review on Reviewable](https://reviewable.io/reviews/servo/rust-mozjs/208)

### CODE REVIEW

**Comment by michaelwu** [comment]
Have you tried using report->ucmessage?

**Comment by eefriedman** [comment]
Just tried it... yes, it contains the exact same Latin1 string inflated to u16.

**Comment by michaelwu** [comment]
Hmm I expected it to be the other way around. For example, in http://mxr.mozilla.org/mozilla-central/source/js/src/jscntxt.cpp#650 , ucmessage is the original string before truncation to latin1.

**Comment by eefriedman** [comment]
Added commit to use ucmessage.  You can test for yourself if you want.

**Comment by eefriedman** [comment]
Oops; not sure how I forgot it was in the standard library.  Updated.

**Comment by eefriedman** [comment]
@michaelwu Ping.

**Comment by eefriedman** [comment]
Nothing is happening here; do I need to file a bug against saltfs or something?

**Comment by jdm** [comment]
@bors-servo: r=michaelwu
I had to re-synchronize homu's queue for rust-mozjs.

**Comment by eefriedman** [comment]
The build timed out during the Spidermonkey build.  The configuration probably needs to be changed somehow.

**Comment by jdm** [comment]
Bah, we're being bitten by libc here. #211 needs to merge first.

**Pull request merged**
