### PR TITLE
Update to mozjs 86.

### PR DESCRIPTION
**Pull request by jdm**
Integrates the work from https://github.com/servo/mozjs/pull/268.

### CODE REVIEW

**Comment by jdm** [comment]
@sagudev I did the intermediate work here; if you feel like using this branch to update Servo, go ahead!

**Comment by sagudev** [comment]
Actually, I have already everything prepared in my fork.

**Comment by jdm** [comment]
Oh, nice!

**Comment by sagudev** [comment]
How far is GitHub actions for Servo repo? The main reason I implemented GitHub Actions for servo/(rust-)mozjs is to quickly test changes in my own form. Travis kicked me out and never used Appvenoy before. Anything I can do there to speed up bringing GH actions to main servo repo?

**Comment by jdm** [comment]
https://github.com/servo/servo/pull/27865 is all of the work to date. The only thing stopping it from merging is solving the issue of Windows builds; we need to clone to the C:\ drive instead of the default because we run out of disk space, but that means we can't use the default checkout action and replicating that in the yml is tricky.

**Comment by sagudev** [comment]
I cloned servo/mozjs on windows to C drive before CARGO_HOME heck.

**Comment by jdm** [comment]
https://github.com/servo/rust-mozjs/pull/529/commits/67bd23f8b05511610f4d40435931651de3fa93bb

Oh, I never thought of doing a copy. That looks like a great solution!

**Comment by sagudev** [comment]
> 
> 
> [67bd23f](https://github.com/servo/rust-mozjs/commit/67bd23f8b05511610f4d40435931651de3fa93bb)


That's what I wanted to say.

**Pull request closed without merging**
