### PR TITLE
Work around Windows arm64 crashes

### PR DESCRIPTION
**Pull request by jdm**
This creates a nicer API around the RealmOptions changes from https://github.com/servo/mozjs/pull/191. This also works around crashes encountered when passing jsid values by value.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-mozjs/467)

### CODE REVIEW

**Comment by jdm** [comment]
This needs to wait for https://github.com/servo/mozjs/pull/191 to merge first.

**Comment by CYBAI** [comment]
<details>
<summary>In AppVeyor</summary>

```
error[E0599]: no function or associated item named `default` found for type `mozjs::jsapi::RealmOptions` in the current scope
  --> tests\evaluate.rs:27:47
   |
27 |                                &RealmOptions::default())
   |                                               ^^^^^^^ function or associated item not found in `mozjs::jsapi::RealmOptions`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0599`.
The following warnings were emitted during compilation:
warning: In file included from <built-in>:1:
warning: C:\projects\rust-mozjs\target\x86_64-pc-windows-msvc\debug\build\mozjs_sys-994add0909aabfcd\out\js\src\js-confdefs.h(50,9): warning: 'WIN32' macro redefined [-Wmacro-redefined]
warning: #define WIN32 1
warning:         ^
warning: <command line>(3,9): note: previous definition is here
warning: #define WIN32
warning:         ^
warning: In file included from src/jsglue.cpp:15:
warning: In file included from C:\projects\rust-mozjs\target\x86_64-pc-windows-msvc\debug\build\mozjs_sys-994add0909aabfcd\out\dist\include\jsapi.h:12:
warning: In file included from C:\projects\rust-mozjs\target\x86_64-pc-windows-msvc\debug\build\mozjs_sys-994add0909aabfcd\out\dist\include/mozilla/AlreadyAddRefed.h:12:
warning: C:\projects\rust-mozjs\target\x86_64-pc-windows-msvc\debug\build\mozjs_sys-994add0909aabfcd\out\dist\include\mozilla/Assertions.h(219,1): warning: function declared 'noreturn' should not return [-Winvalid-noreturn]
warning: }
warning: ^
warning: In file included from src/jsglue.cpp:15:
warning: In file included from C:\projects\rust-mozjs\target\x86_64-pc-windows-msvc\debug\build\mozjs_sys-994add0909aabfcd\out\dist\include\jsapi.h:29:
warning: In file included from C:\projects\rust-mozjs\target\x86_64-pc-windows-msvc\debug\build\mozjs_sys-994add0909aabfcd\out\dist\include/js/CallArgs.h:72:
warning: C:\projects\rust-mozjs\target\x86_64-pc-windows-msvc\debug\build\mozjs_sys-994add0909aabfcd\out\dist\include\js/RootingAPI.h(762,8): warning: 'dllexport' attribute ignored [-Wignored-attributes]
warning: struct JS_PUBLIC_API MovableCellHasher<JS::Heap<T>> {
warning:        ^
warning: C:\projects\rust-mozjs\target\x86_64-pc-windows-msvc\debug\build\mozjs_sys-994add0909aabfcd\out\dist\include\jstypes.h(47,25): note: expanded from macro 'JS_PUBLIC_API'
warning: #  define JS_PUBLIC_API MOZ_EXPORT
warning:                         ^
warning: C:\projects\rust-mozjs\target\x86_64-pc-windows-msvc\debug\build\mozjs_sys-994add0909aabfcd\out\dist\include\mozilla/Types.h(41,35): note: expanded from macro 'MOZ_EXPORT'
warning: #    define MOZ_EXPORT __declspec(dllexport)
warning:                                   ^
warning: 3 warnings generated.
error: Could not compile `mozjs`.
```

</details>

<details>
<summary>In Travis</summary>

```
warning: trait objects without an explicit `dyn` are deprecated
 --> src/panic.rs:9:55
  |
9 | thread_local!(static PANIC_RESULT: RefCell<Option<Box<Any + Send>>> = RefCell::new(None));
  |                                                       ^^^^^^^^^^ help: use `dyn`: `dyn Any + Send`
  |
  = note: `#[warn(bare_trait_objects)]` on by default
warning: trait objects without an explicit `dyn` are deprecated
 --> src/panic.rs:9:55
  |
9 | thread_local!(static PANIC_RESULT: RefCell<Option<Box<Any + Send>>> = RefCell::new(None));
  |                                                       ^^^^^^^^^^ help: use `dyn`: `dyn Any + Send`
warning: trait objects without an explicit `dyn` are deprecated
 --> src/panic.rs:9:55
  |
9 | thread_local!(static PANIC_RESULT: RefCell<Option<Box<Any + Send>>> = RefCell::new(None));
  |                                                       ^^^^^^^^^^ help: use `dyn`: `dyn Any + Send`
  |
  = note: `#[warn(bare_trait_objects)]` on by default
warning: trait objects without an explicit `dyn` are deprecated
 --> src/panic.rs:9:55
  |
9 | thread_local!(static PANIC_RESULT: RefCell<Option<Box<Any + Send>>> = RefCell::new(None));
  |                                                       ^^^^^^^^^^ help: use `dyn`: `dyn Any + Send`
     Running `rustc --crate-name evaluate tests/evaluate.rs --color always --emit=dep-info,link -C debuginfo=2 --test -C metadata=5128c4bb7ac09cc7 -C extra-filename=-5128c4bb7ac09cc7 --out-dir /home/travis/build/servo/rust-mozjs/target/debug/deps -C incremental=/home/travis/build/servo/rust-mozjs/target/debug/incremental -L dependency=/home/travis/build/servo/rust-mozjs/target/debug/deps --extern lazy_static=/home/travis/build/servo/rust-mozjs/target/debug/deps/liblazy_static-d197baf3c1fb81da.rlib --extern libc=/home/travis/build/servo/rust-mozjs/target/debug/deps/liblibc-f527a8547dbd0338.rlib --extern log=/home/travis/build/servo/rust-mozjs/target/debug/deps/liblog-1339569509fd2d00.rlib --extern mozjs=/home/travis/build/servo/rust-mozjs/target/debug/deps/libmozjs-9e865939887e7e09.rlib --extern mozjs_sys=/home/travis/build/servo/rust-mozjs/target/debug/deps/libmozjs_sys-535fae7bf3719c06.rlib --extern num_traits=/home/travis/build/servo/rust-mozjs/target/debug/deps/libnum_traits-b3320ff1eaae551b.rlib -L native=/home/travis/build/servo/rust-mozjs/target/debug/build/mozjs-51caf84094ca490b/out -L native=/home/travis/build/servo/rust-mozjs/target/debug/build/mozjs_sys-4594251bc03ec97f/out/js/src/build -L native=/home/travis/build/servo/rust-mozjs/target/debug/build/mozjs_sys-4594251bc03ec97f/out -L native=/usr/lib/x86_64-linux-gnu`
error[E0599]: no function or associated item named `default` found for type `mozjs::jsapi::RealmOptions` in the current scope
  --> tests/evaluate.rs:27:47
   |
27 |                                &RealmOptions::default())
   |                                               ^^^^^^^ function or associated item not found in `mozjs::jsapi::RealmOptions`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0599`.
error: Could not compile `mozjs`.
```

</details>

**Pull request merged**
