### PR TITLE
Make Rooted do its job.

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-mozjs/326)

### CODE REVIEW

**Comment by Ms2ger** [comment]
My main fear is that the two out-of-line calls will be terrible for performance. I don't suppose we use `Rooted` terribly often…

**Comment by Ms2ger** [comment]
@jdm can you check the fixup commit? I'm not sure if the additional unsafety is worth it.

**Comment by jdm** [comment]
As mentioned on IRC, I think we should follow jonco's suggestion from https://github.com/servo/servo/issues/13096#issuecomment-250901349 rather than pursue the patch I wrote in that issue.

**Comment by jdm** [comment]
I'm glad to see the test, though!

**Comment by jdm** [comment]
@bors-servo: r+
Nice.

**Pull request merged**
