### PR TITLE
start tidying

### PR DESCRIPTION
**Pull request by edunham**
for https://github.com/servo/servo/issues/10636

Some license recognition failures are waiting on https://github.com/servo/servo/pull/10721 to land.

There are 214 lines over 120 characters in this project, many of which I don't think there's a good way to shorten. Should I update tidy to make the line length check optional?

---

This change is [Reviewable](https://reviewable.io/reviews/servo/rust-mozjs/255)

### CODE REVIEW

**Comment by tschneidereit** [comment]
Note that the `jsapi_*` files are auto-generated. I don't think it makes too much sense to tidy them.

**Comment by jdm** [comment]
Making it possible for tidy to read a per-repo config file that can ignore certain files might be the best way forward.

**Comment by metajack** [comment]
Does it make sense for it just to read .gitignore?

**Comment by jdm** [comment]
No, because our bindgen-generated files aren't in that.

**Comment by metajack** [comment]
Aren't bindgen generated files generated out of the source tree somewhere under `target/`? `target/` is certainly in .gitignore.

**Comment by jdm** [comment]
No, they're checked into the main repository. We don't run bindgen on every build.

**Comment by jdm** [comment]
Note how big this PR is for why this is a thing to be concerned about :)

**Comment by jdm** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
