### PR TITLE
Update etc/bindings.sh for the new bindgen flag format

### PR DESCRIPTION
**Pull request by fitzgen**
r? @emilio

---
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-mozjs/300)

### CODE REVIEW

**Comment by emilio** [comment]
I'd have expected you to need to put `wrapper.h` after everything else, but if not, r=me

**Comment by fitzgen** [comment]
> I'd have expected you to need to put wrapper.h after everything else, but if not, r=me

It is after all the normal flags, but before -- and the flags that get passed through to clang.

**Comment by emilio** [comment]
@fitzgen: Yeah, I mean, for the `-x c++ -std=c++11` to be effective, I think you need to give the filename after it?

Anyway, I guess you've tested it, so feel free to invoke bors with `r=emilio`

**Pull request merged**
