### PR TITLE
Expose IntoMutableHandle API.

### PR DESCRIPTION
**Pull request by jdm**
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-mozjs/455)

### CODE REVIEW

**Comment by jdm** [comment]
As far as I can tell not exposing this is just an oversight.

**Comment by jdm** [comment]
Ping @asajeffrey

**Comment by CYBAI** [comment]
@bors-servo retry

(Can bors retry travis? 🤔)

```
curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 60
Error: Failed to download resource "llvm"
Download failed: https://homebrew.bintray.com/bottles/llvm-8.0.0_1.high_sierra.bottle.tar.gz
```

**Comment by jdm** [comment]
It's easier to restart the single failed job in the travis interface.

**Comment by CYBAI** [comment]
hmm, seems I cannot restart the job for Travis in this repo 😖

**Pull request merged**
