### PR TITLE
Enable debug testing.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/rust-mozjs/247)

### CODE REVIEW

**Comment by Ms2ger** [comment]
@bors-servo retry
* #246

**Comment by larsbergstrom** [comment]
```
     Running `/home/travis/build/servo/rust-mozjs/target/debug/js-290d59709cc979d2`

running 2 tests

Hit MOZ_CRASH(contention for interrupt signal) at /home/travis/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/asmjs/AsmJSSignalHandlers.cpp:1268

Process didn't exit successfully: `/home/travis/build/servo/rust-mozjs/target/debug/js-290d59709cc979d2` (signal: 11, SIGSEGV: invalid memory reference)

```

**Comment by Ms2ger** [comment]
https://github.com/servo/rust-mozjs/pull/252

**Pull request closed without merging**
