### PR TITLE
Make Runtime::new safe

### PR DESCRIPTION
**Pull request by nox**
CC @tschneidereit @Ms2ger @jdm

---
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-mozjs/267)

### CODE REVIEW

**Comment by tschneidereit** [comment]
Looks good with comments addressed. Using a lazy static is a nice solution.

<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> #### Make Runtime::new safe
> 
> CC @tschneidereit @Ms2ger @jdm
> 
> 
> 
</details>


---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/rust.rs, line 122 \[r1\]](https://reviewable.io:443/reviews/servo/rust-mozjs/267#-KJ1cbP0z76ASsUFqiDZ:-KJ1cbP0z76ASsUFqiD_:2012083994) ([raw file](https://github.com/servo/rust-mozjs/blob/7d74a38367d462084802e1e3f2d0aab99877713b/src/rust.rs#L122)):*
> ```Rust
>     pub unsafe fn new(parent_rt: *mut JSRuntime) -> Runtime {
>         let js_runtime = JS_NewRuntime(default_heapsize, ChunkSize as u32, parent_rt);
>         assert!(!js_runtime.is_null());
> ```

We still need this assert or some other form of null check. Creating a child runtime is just as fallible as creating the parent runtime, after all.

---

*[src/rust.rs, line 125 \[r1\]](https://reviewable.io:443/reviews/servo/rust-mozjs/267#-KJ1cj9bFTm7b346r-M_:-KJ1cj9bFTm7b346r-Ma:916274856) ([raw file](https://github.com/servo/rust-mozjs/blob/12ff240df79855f73812acc1b4a856a99c58aafc/src/rust.rs#L125)):*
> ```Rust
>                         assert!(JS_Init());
>                         let runtime = JS_NewRuntime(
>                             default_heapsize, ChunkSize as u32, ptr::null_mut());
> ```

This should use as small a heap size as possible. The only JS ever running in here should be the self-hosted code. Not sure how best to figure out a good value, though.

---

*[src/rust.rs, line 128 \[r1\]](https://reviewable.io:443/reviews/servo/rust-mozjs/267#-KJ1dLPa48QvfT0zM7Ru:-KJ1dLPbuUq5x1FgfY28:-1902210990) ([raw file](https://github.com/servo/rust-mozjs/blob/12ff240df79855f73812acc1b4a856a99c58aafc/src/rust.rs#L128)):*
> ```Rust
>                         assert!(!runtime.is_null());
>                         let context = JS_NewContext(
>                             runtime, default_stacksize as size_t);
> ```

Much more important than the heap size, and should be much smaller. 1/16th (512kb) might well be enough, or even 1/32th (256kb).

---

*[src/rust.rs, line 130 \[r1\]](https://reviewable.io:443/reviews/servo/rust-mozjs/267#-KJ1esMNQR5MemBcxVxU:-KJ1esMNQR5MemBcxVxV:-1680908504) ([raw file](https://github.com/servo/rust-mozjs/blob/12ff240df79855f73812acc1b4a856a99c58aafc/src/rust.rs#L130)):*
> ```Rust
>                             runtime, default_stacksize as size_t);
>                         assert!(!context.is_null());
>                         TopRuntime(runtime)
> ```

It might make sense to trigger a compacting GC at this point, as no new code execution should happen in this runtime afterwards. I also wonder if we can write-protect the runtime's heap afterwards?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/rust-mozjs/267#-:-KJ1fTSUcKRqCrvKem5-:1628671525)*

**Comment by tschneidereit** [comment]
@jandem informs me that both the stack and the heap are allocated lazily, so I guess my comments on their sizes can be safely ignored.

**Comment by nox** [comment]
Put back the assertion. LGTM?

<details><summary><i>Previously, tschneidereit (Till Schneidereit) wrote…</i></summary>
> @jandem informs me that both the stack and the heap are allocated lazily, so I guess my comments on their sizes can be safely ignored.
</details>


---

Review status: 8 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/rust.rs, line 122 \[r1\]](https://reviewable.io:443/reviews/servo/rust-mozjs/267#-KJ1cbP0z76ASsUFqiDZ:-KJ1n8ZLB4Gh0UmL37OO:1324943802) ([raw file](https://github.com/servo/rust-mozjs/blob/7d74a38367d462084802e1e3f2d0aab99877713b/src/rust.rs#L122)):*
<details><summary><i>Previously, tschneidereit (Till Schneidereit) wrote…</i></summary>
> We still need this assert or some other form of null check. Creating a child runtime is just as fallible as creating the parent runtime, after all.
</details>
Done. That was mistakenly removed.

---

*[src/rust.rs, line 125 \[r1\]](https://reviewable.io:443/reviews/servo/rust-mozjs/267#-KJ1cj9bFTm7b346r-M_:-KJ1mslWCvAsMPvcJuLf:791938894) ([raw file](https://github.com/servo/rust-mozjs/blob/12ff240df79855f73812acc1b4a856a99c58aafc/src/rust.rs#L125)):*
<details><summary><i>Previously, tschneidereit (Till Schneidereit) wrote…</i></summary>
> This should use as small a heap size as possible. The only JS ever running in here should be the self-hosted code. Not sure how best to figure out a good value, though.
</details>
So I don't need to do anything right? Following your last comment.

---

*[src/rust.rs, line 128 \[r1\]](https://reviewable.io:443/reviews/servo/rust-mozjs/267#-KJ1dLPa48QvfT0zM7Ru:-KJ1n0-rsxYGQlk54FJT:2136969779) ([raw file](https://github.com/servo/rust-mozjs/blob/12ff240df79855f73812acc1b4a856a99c58aafc/src/rust.rs#L128)):*
<details><summary><i>Previously, tschneidereit (Till Schneidereit) wrote…</i></summary>
> Much more important than the heap size, and should be much smaller. 1/16th (512kb) might well be enough, or even 1/32th (256kb).
</details>
Same question.

---

*[src/rust.rs, line 130 \[r1\]](https://reviewable.io:443/reviews/servo/rust-mozjs/267#-KJ1esMNQR5MemBcxVxU:-KJ1n1MsLLlobpcaQXF8:2136969779) ([raw file](https://github.com/servo/rust-mozjs/blob/12ff240df79855f73812acc1b4a856a99c58aafc/src/rust.rs#L130)):*
<details><summary><i>Previously, tschneidereit (Till Schneidereit) wrote…</i></summary>
> It might make sense to trigger a compacting GC at this point, as no new code execution should happen in this runtime afterwards. I also wonder if we can write-protect the runtime's heap afterwards?
</details>
Same question.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/rust-mozjs/267#-:-KJ1nGcOR1xhH9Kyr-pZ:976431721)*

**Comment by tschneidereit** [comment]
Yes, LGTM.

<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> Put back the assertion. LGTM?
</details>


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/rust-mozjs/267#-:-KJ1nox8bb3MUT_Dn2yf:340681380)*

**Pull request merged**
