### PR TITLE
Implement FromJSValConvertible for *mut JSObject

### PR DESCRIPTION
**Pull request by KiChjang**
r? @Ms2ger or @nox

---
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-mozjs/321)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Doesn't compile

**Comment by KiChjang** [comment]
Uhh right, stupid me.

**Comment by Ms2ger** [comment]
These implementations crash if handed the wrong type of value. Is that intentional?

**Comment by KiChjang** [comment]
I essentially copied the implementation from JSVal. Shall I instead check that it is an object first, and if not, return an Err(()) or a ConversionResult::Failure?

**Comment by Ms2ger** [comment]
Let's take a step back. Why did you make this PR?

**Comment by KiChjang** [comment]
MessagePort contains a WebIDL method that looks like this:
```
  void postMessage(any message, optional sequence<object> transfer = []);
```
And so CodegenRust.py is trying to convert a JS HandleValue to a JS object, which currently doesn't exist in rust-mozjs bindings.

**Comment by jdm** [comment]
Given that this is only needed because of codegen for a feature we don't support yet (transferrable objects), I propose we use `optional any transfer` and close this PR.

**Pull request closed without merging**
