### PR TITLE
Use ccache

### PR DESCRIPTION
**Pull request by Manishearth**
Not sure if this works.

r? @larsbergstrom

[Review on Reviewable](https://reviewable.io/reviews/servo/rust-mozjs/241)

### CODE REVIEW

**Comment by jdm** [comment]
```
configure: error: ccache not found

make: *** [all] Error 1

thread '<main>' panicked at 'assertion failed: result.success()', /home/travis/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/build.rs:17
```

**Comment by jdm** [comment]
Want to rebase and squash this? It seems like the second commit worked.

**Comment by Manishearth** [comment]
Done

**Pull request merged**
