### PR TITLE
Store the JSContext in TLS for easy access.

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-mozjs/322)

### CODE REVIEW

**Comment by nox** [comment]
Why not put the TLS thing in servo/servo? Why forbid the creation of two unrelated runtimes on a single thread?

**Comment by fitzgen** [comment]
> Why forbid the creation of two unrelated runtimes on a single thread?

SpiderMonkey requires a 1:1 relationship between a `JSRuntime` and its thread.

**Comment by nox** [comment]
@fitzgen Thanks!

@Ms2ger Could you make `::get()` panic if the pointer is null?

**Comment by nox** [comment]
I still believe that was the wrong way to go, because now if we want to use the `Runtime` value and `Runtime::get` to do safe abstractions around for example `ToJsValConvertible`, we still won't be able to avoid some unsafe code in servo for dereferencing the result of `Runtime::get`, whereas we could make it be owned by TLS if it were done in servo instead of here.

**Pull request merged**
